services:

  apache:
    build: .
    container_name: moodle_apache
    depends_on:
    - db
    ports:
    - 8080:80
    volumes:
    - ./moodle:/var/www/html
    - ./moodle_data:/var/www/moodledata
    - ./quickcodeia:/var/www/html/mod/quickcodeia
    environment:
    - MOODLE_DBTYPE=mysqli
    - MOODLE_DBHOST=db
    - MOODLE_DBNAME=moodle
    - MOODLE_DBUSER=moodleuser
    - MOODLE_DBPASS=moodlepassword
    tty: true

  db:
    image: mysql:8.0
    container_name: moodle_db
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepassword
    volumes:
    - ./mysql_data:/var/lib/mysql

  quickcodeia_coderunner:
    build:
      context: ./quickcodeia_coderunner
    image: quickcodeia-coderunner
    container_name: quickcodeia_coderunner
    ports:
    - 8081:8000
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
    - 11434:11434
    volumes:
    - ./ollama_data:/root/.ollama
    restart: unless-stopped
    tty: true
