version: "3.8"

services:

  apache:
    build: .
    container_name: moodle_apache
    depends_on:
      - db
    expose:
      - "80"
    volumes:
      - ./moodle:/var/www/html
      - ./moodle_data:/var/www/moodledata
      - ./quickcodeia:/var/www/html/mod/quickcodeia
    environment:
      - MOODLE_DBTYPE=mysqli
      - MOODLE_DBHOST=db
      - MOODLE_DBNAME=moodle
      - MOODLE_DBUSER=moodleuser
      - MOODLE_DBPASS=moodlepassword
    tty: true
    networks:
      - moodle_network

  db:
    image: mysql:8.0
    container_name: moodle_db
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepassword
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - moodle_network

  quickcodeia_coderunner:
    build:
      context: ./quickcodeia_coderunner
    image: quickcodeia-coderunner
    container_name: quickcodeia_coderunner
    ports:
      - "8081:8000"
    restart: unless-stopped
    networks:
      - moodle_network

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    restart: unless-stopped
    tty: true
    networks:
      - moodle_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - apache
    networks:
      - moodle_network
      
networks:
  moodle_network:
    name: moodle_network
